### ISSUE TITLE
시설물 변환(심볼) 기능 개선 [기능명칭변경 -> LOD2]

### ISSUE THREAD

**Issue by iyeti78** [EgisCorp/XDWORLD-Builder-Professional#13]
요청일자 : 2023-09-07
![image](https://github.com/EgisCorp/XDWORLD-Builder-Professional/assets/39153654/19f6876e-2d70-4da7-94ab-64b073222d39)
![image](https://github.com/EgisCorp/XDWORLD-Builder-Professional/assets/39153654/15b21882-558f-4705-b16f-b4aef4c52a29)

**Comment by egiskorea-ryong** [comment]
기존 XDO 가공기능 유지.
LOD2 가공 기능 추가중.
