### ISSUE TITLE
드론 LOD와 기능 중복 아이콘 및 병합 기능 개선  [기능 명칭 변경 → 드론 Mesh]

### ISSUE THREAD

**Issue by iyeti78** [EgisCorp/XDWORLD-Builder-Professional#15]
요청일자 : 2023-09-07
![image](https://github.com/EgisCorp/XDWORLD-Builder-Professional/assets/39153654/3f89b676-15fe-4969-9c56-d790a0b287d5)

**Comment by YangHeeBong** [comment]
## 드론 매쉬 기본화면

![image](https://github.com/EgisCorp/XDWORLD-Builder-Professional/assets/82924515/ec559d31-1621-4cb4-8d83-a834a5e3d46c)

## 원본파일 선택 시 3가지 기능을 제공
### 1. .dae 파일 선택 
![image](https://github.com/EgisCorp/XDWORLD-Builder-Professional/assets/82924515/80aa8917-4327-4623-8823-471c22abdafb)
### 2. .xml 파일 선택
![image](https://github.com/EgisCorp/XDWORLD-Builder-Professional/assets/82924515/d8fe90e3-908e-46b4-831c-b65729d2a9cb)
### 3. COLLADA 포맷이 아닌 경우 
![image](https://github.com/EgisCorp/XDWORLD-Builder-Professional/assets/82924515/49e7f83b-4b4c-46c3-8b8e-948540ade5c6)

## dae 파일 선택에 따른 기능 변경
 - dae 단독 변환

### UI 화면 변경

![image](https://github.com/EgisCorp/XDWORLD-Builder-Professional/assets/82924515/62654529-19c5-4a63-8203-a58977859f77)

#### 변경 내용
 - 설정
   - 생성레벨
   - 렌더링 옵션(추가) : cw, ccw 면 설정
 - DAE 설정
   - 회전기준 : 지구본 중심, 객체 원점 (추후 명칭 정리)
   - 생성위치 
     - Longitude : 가공될 객체 경도 위치 좌표
     - Latitude : 가공될 객체 위도 위치 좌표
     - Altitude : 가공될 객체 고도 위치 좌표
     - 좌표계 : DAE COLLADA 포맷을 구성하는 좌표값을 EPSG 좌표계 값 설정
 - 파일정보
   - 단위 : DAE  COLLADA 포맷에 적용된 기본 길이 단위(밀리미터, 센티미터, 미터, 인치) 

## xml 파일 선택에 따른 기능 변경
- 드론 mesh 변환 기능
- 기존 드론 LOD 변환과 동일

### UI 화면 변경

![image](https://github.com/EgisCorp/XDWORLD-Builder-Professional/assets/82924515/7df65ded-4bc9-4a1f-af85-b973fb40d334)


#### 변경 내용
- 기능 드론 LOD 방법과 동일

**Comment by YangHeeBong** [comment]
# DT빌더 상에서의 높이(Z값) 가시화 오류 조치

Z값 오차는 다음과 같은 원인입니다.

- 드론 촬영 시 설정된 고도값이 높은 경우
- 기계의 고도 값이 다른 경우
 
빌더는 드론 메시를 구성하는 DAE 파일에서 설정된 좌표 값을 기준으로 변환합니다.
만약 지형 결합을 통해 높이 조절 시 기준점을 임의로 잡아야 하고, 이 임의의 기준점 선택에 따라 지형 밑으로 드론 메시가 묻히거나 공중으로 뜨는 현상이 발생할 수 있으므로, 이 문제는 가공 후 드론 메시 높이 조절을 통해 처리해야 합니다.
