### ISSUE TITLE
DAE와 기능 중복 아이콘 및 병합 기능 개선 [기능 명칭 변경 → 드론 Mesh]

### ISSUE THREAD

**Issue by iyeti78** [EgisCorp/XDWORLD-Builder-Professional#16]
요청일자 : 2023-09-07
![image](https://github.com/EgisCorp/XDWORLD-Builder-Professional/assets/39153654/6b8b172a-6c0f-4e0b-a869-99b1013b3959)

**Comment by YangHeeBong** [comment]
[내용 유사](https://github.com/EgisCorp/XDWORLD-Builder-Professional/issues/15)
