### ISSUE TITLE
LOD1 오류사항

### ISSUE THREAD

**Issue by EgisCorp** [EgisCorp/XDWORLD-Builder-Professional#2]
LOD1 지형결합, 건물지반 방식 추가

▶ LOD1 카테고리 변경 없음
가공 실행시 프로그램 셧다운 현상 발생
건물바닥높이 활용 외 자동지형결합 기능 누락

**Comment by EgisCorp** [comment]
안녕하세요.

요청하신 첫번째 문의 대해서 좀더 명확한 상황 파악을 위해서 질의를 드리고 두번째 문의에 대해서는 답변을 드립니다.

가공 실행시 프로그램 셧다운 현상 발생
==> 가공 실행이 진행하고 있는 중에 셧다운 현상인지? 아니면 가공 버튼을 누르자 마자 셧다운인지 궁금합니다.
==> 종료시 뜨는 화면 스크린 샷 보내주실수 있습니까?

건물바닥높이 활용 외 자동지형결합 기능 누락
==> 기능 추가 가능합니다. 대신에 가공 시간이 더 오래 걸릴 수 있으며 지형 결합에 사용할 지형 서비스 데이터가 특정 폴더 내에 있어야 합니다. 지형서비스데이터라 함은 LOD 처리가 된 bil 형태의 지형 정보가 있는 서비스 데이터 폴더 입니다. LOD1 데이터는 최신 데이터이기 때문에 LOD1 포맷에 제공하는 건물 바닥 높이와 지형 서비스 데이터와 맞지 않는 경우가 있습니다. 지형 결합 기능을 선택하면 건물 바닥 높이 필드 선택과 무관하게 지형 서비스 데이터만 고려해서 건물의 바닥 높이를 맞춥니다. 기능 구현에 필요한 지형 서비스 폴더 샘플과 LOD1 shp 파일을 전달해주시면 처리해드리겠습니다.

[builder@egiskorea.com](mailto:builder@egiskorea.com) 로 자료를 보내주시면 됩니다.

감사합니다.

**Comment by EgisCorp** [comment]
1. [버전 1.0.0.2] LOD1 가공 실행시 프로그램 셧다운 현상 발생
   - LOD1 가공 실행 버튼을 누르자 마자 셧다운 진행됩니다. (종료 스크린 샷 캡쳐불가)

     ※ 1-1. 총 6대의 내부 PC 테스트 결과 1대의 PC만 가공 실행됨. 
              별도의 PC 사양 차이는 아닌것으로 판단되어 원인 파악 불가.

        1-2. 9월 27일 부산연구소 윤정식 이사님으로부터 메신저로 전달받은 실행파일의 경우
              기존 설치파일에 실행파일 덮어쓰기하는 형식으로써 LOD1 가공 실행은 되나,
              지형/영상 가시화 및 가공 작업 등의 기존 진행 오류가 발생되어 활용 및 버전 관리 불가


2. [버전 1.0.0.2] LOD1 건물바닥높이 활용 외 자동지형결합 기능 누락
   - LOD1 기능 구현에 필요한 지형 서비스 폴더 샘플 메일 전달 (builder@egiskorea.com)
  
     → DEM(bil) 타일맵 자료 활용하여, 건물 자동지형결합 기능 추가 요청 


     ※ 샘플 데이터 대상지는 청주시 우암산 부근

         * 건물데이터 - 청주시 테스트 건물 SHP.zip 
                              (cj_buld_clip_5186.shp)
         * DEM (bil) - dem_cj_test_5186.zip
         * 정사영상 (dds) - tile_cj_test_5186.zip

**Comment by EgisCorp** [comment]
안녕하세요. 답변을 늦게 드려서 미안합니다.
요청하신 2가지 요구사항에 답변입니다.

LOD1 가공 기능은 이미 기능을 수정하여서 2023년10월 23일 월요일 양희봉 부장이 보낸 병렬처리 가공 기능이 추가된 설치본에 있습니다.
LOD1 지형 결합 기능은 2023년 10월 27일(금)까지 추가해서 보내드리도록 하겠습니다. 마침 23일 보낸 병렬처리 기능이 DDS,JPG,PNF 포맷으로 다 되어야 하는데 DDS,JPG는 되나 PNG 오류가 있어 PNG 가공 오류처리와 함께해서 27일 까지 보내드리겠습니다.
첨부된 이미지는 지형 결합 UI를 포함시킨 것입니다. 설명에 명시한대로 지형 결합 옵션을 선택하면 LOD1 포맷에서 제공하는 건물바닥 높이 옵션은 무시됩니다.
감사합니다.

![image](https://github.com/EgisCorp/XDWORLD-Builder-Professional/assets/84553395/20aee48d-2713-45f3-9519-5df302bbf368)

**Comment by egiskorea** [comment]
안녕하세요 요청하신 위의 기능은 v_5.0.1 버전에 적용하였습니다. 메인페이지 Readme 에 보시면 제품을 다운로드할 수 있는 링크가 있습니다.
