### ISSUE TITLE
(230818 연구소 수급 프로그램) JPGtoDDS 별도 프로그램 추가 기능 개선

### ISSUE THREAD

**Issue by iyeti78** [EgisCorp/XDWORLD-Builder-Professional#20]
요청일자 : 2023-09-07
![image](https://github.com/EgisCorp/XDWORLD-Builder-Professional/assets/39153654/71cdbede-598d-4ef8-9974-d80d76f46052)

**Comment by YangHeeBong** [comment]
기능 완료
