### ISSUE TITLE
가공 완료 후 레이어 창 내 최종 파일명 가시화 기능 개선

### ISSUE THREAD

**Issue by iyeti78** [EgisCorp/XDWORLD-Builder-Professional#21]
요청일자 : 2023-09-07
![image](https://github.com/EgisCorp/XDWORLD-Builder-Professional/assets/39153654/a8a71b59-70e4-4f50-a4f6-4b4ab9a1757f)

**Comment by YangHeeBong** [comment]
레이어 명칭 없는 경우 폴더 명칭으로 고정
