### ISSUE TITLE
건물 등 선택 시 파일명 속성 확인 기능 개선 (현재 확인 불가)

### ISSUE THREAD

**Issue by iyeti78** [EgisCorp/XDWORLD-Builder-Professional#22]
요청일자 : 2023-09-07
![image](https://github.com/EgisCorp/XDWORLD-Builder-Professional/assets/39153654/7acdb183-9f45-4cf5-845e-af10fdda9a56)

**Comment by YangHeeBong** [comment]
![image](https://github.com/user-attachments/assets/77424d9e-0f2f-4c46-a64e-460e3347d5d0)

현재 속성 정보 기능을 구현하고 있습니다. 

아직 몇가지 발생 이벤트 처리와 시설물 가공기능에 대한 속성정보처리가 완료 된다면 제공지를 통해 알려드리겠습니다.
