### ISSUE TITLE
모델/위치 좌표기준값을 활용한 타일맵 가공 추가 기능 개선

### ISSUE THREAD

**Issue by iyeti78** [EgisCorp/XDWORLD-Builder-Professional#24]
요청일자 : 2023-10-19
![image](https://github.com/EgisCorp/XDWORLD-Builder-Professional/assets/39153654/771afbf7-6f80-459a-8edb-16322a6af28c)
![image](https://github.com/EgisCorp/XDWORLD-Builder-Professional/assets/39153654/b87d0ab2-50de-4c63-b80d-711e1ae40e66)

**Comment by YangHeeBong** [comment]
3d 모델 데이터 필요

**Comment by egiskorea-ryong** [comment]
위치, 모델 좌표 기준 가공 기능은 추후 obj, 3ds 등 여러 객체를 통합해서 범용적으로 사용할수있도록 기능 개발

**Comment by egiskorea-ryong** [comment]
5.1 버전 이후로 정상 동작
