### ISSUE TITLE
병렬처리로 대용량 정사영상 타일링 시 가공 진행 중 셧다운 후 재부팅 현상 발생

### ISSUE THREAD

**Issue by iyeti78** [EgisCorp/XDWORLD-Builder-Professional#26]
요청일자 : 2023-10-27
> 해당 현상 발생 시점 또는 특정 파일 및 가공 수량 불분명
> 51장까지는 정상 실행 확인하였으며, 약 100장 가공 진행 중 해당 현상 발생

**Comment by egiskorea** [comment]
병렬 처리  도중 다운 되는 현상은 다양한 장비의 특성에 따라 발생합니다. 오류에 대한 처리는 이슈 발생마다 case by case 형태로 개선을 지속적으로 해 나가고 있습니다. 
병렬 처리 중 다운 되는 경우 처음 부터 재가공하는 것을 줄이기 위해서 내부적으로 가공 작업 로그를 관리하고 있기 때문에 원본과 대상 폴더가 같다면 이전 작업했던 이후 부터 가공이 진행됩니다.
