### ISSUE TITLE
기능 창 상단 서브메뉴에 마우스포인트 오버 시 서브메뉴명 표출

### ISSUE THREAD

**Issue by iyeti78** [EgisCorp/XDWORLD-Builder-Professional#41]
> 기능명 카테고리 글자 뚜렷하게 변경(색상 변경 등)
> 기능창 하단 내 설명 디테일하게 수정
> 아이콘 이미지 품질 개선
> 창 인터페이스 명칭 누락

![image](https://github.com/EgisCorp/XDWORLD-Builder-Professional/assets/39153654/e2a65c88-6e06-42f8-a5af-7dc5fc4bd4e2)
![image](https://github.com/EgisCorp/XDWORLD-Builder-Professional/assets/39153654/19f47aae-42ef-4659-a779-410a22432b21)

**Comment by YangHeeBong** [comment]
이미지 품질 개선은 추후 예정

**Comment by egiskorea-ryong** [comment]
* 기능명 카테고리 글자 뚜렷하게 변경
* 아이콘 이미지 품질 개선
* 창 인터페이스 명칭 누락

수정하였습니다.
