### ISSUE TITLE
프로그램 내 RAW 데이터 기본 탑재

### ISSUE THREAD

**Issue by iyeti78** [EgisCorp/XDWORLD-Builder-Professional#46]
![image](https://github.com/EgisCorp/XDWORLD-Builder-Professional/assets/39153654/cbce69c8-0a45-4718-99ca-5377442bef9a)

**Comment by egiskorea** [comment]
RAW 데이터가 설치본에 같이 포함되어 있습니다. 지형, 영상 가공시에 해당 RAW 데이터를 대상 폴더에 먼저 내부적으로 복사를 한 후에 가공을 시작합니다. 대신 RAW 데이터 용량이 작습니다.

용량이 큰 RAW 데이터의 경우는 설치본으로 함께 배포하기는 어렵습니다.

따로 보유하고 계시는 RAW 데이터의 경우는 가공시에 대상 폴더에 복사를 먼저 한 후 사용하시는 것을 권장합니다.
