### ISSUE TITLE
지형 가공시 NO DATA 영역 및 DEM 외곽 영역 지형 꺼짐 현상 발생

### ISSUE THREAD

**Issue by iyeti78** [EgisCorp/XDWORLD-Builder-Professional#47]
![image](https://github.com/EgisCorp/XDWORLD-Builder-Professional/assets/39153654/1363eb82-fb00-4555-8366-269537979484)

**Comment by egiskorea** [comment]
지형 가공 NoData 처리하였습니다.

NoData  설정 화면
![nodata](https://github.com/EgisCorp/XDWORLD-Builder-Professional/assets/7932812/022f6bfe-36be-43f8-ace1-14954e9d0ca2)

NoData  미설정 시 지형 가공 결과
![nodata_미설정](https://github.com/EgisCorp/XDWORLD-Builder-Professional/assets/7932812/8c4eac9e-efa5-4e9a-b47b-1297792b0e91)

NoData 설정 후 지형 가공 결과
![nodata_설정후](https://github.com/EgisCorp/XDWORLD-Builder-Professional/assets/7932812/0a269897-5424-4179-b91f-0b25db104cc7)

NoData 확인 방법
Global Mapper 에서
![nodata_GlobalMapper](https://github.com/EgisCorp/XDWORLD-Builder-Professional/assets/7932812/5e5c5892-5bed-4861-a086-2bad5f00c426)

QGIS에서
![nodata_QGIS](https://github.com/EgisCorp/XDWORLD-Builder-Professional/assets/7932812/6fb525e2-d890-41a4-9c59-596edfd9b5c4)

**Comment by cheon-saeyeong** [comment]
금일 5.1.0버전 설치 후 테스트 결과,
1. 일부 PC에서 지형 타일맵 생성이 되지 않습니다
    ㄴ 타일맵 폴더는 생성되나 bil 파일 생성 X
2. EPSG:5186 외 좌표계의 경우 여전히 해당 현상이 발생합니다

해당 오류 확인 부탁드립니다.
