### ISSUE TITLE
타일맵 구축 진행 과정 가시화 기능 개선

### ISSUE THREAD

**Issue by iyeti78** [EgisCorp/XDWORLD-Builder-Professional#52]
![image](https://github.com/EgisCorp/XDWORLD-Builder-Professional/assets/39153654/752ab76c-3740-4c5f-81bb-ec31aed29e0e)

**Comment by egiskorea** [comment]
요청하신 내용은 가공 중에 생성된 부분 부분 데이터를 화면에 표현해달라는 요청인거 같습니다. LOD 구조로 원본 데이터를 가공하는데 가공 된 부분만 표현하기에는 LOD가 중간에 온전하게 만들어지지 않기 때문에 요청하신 내용은 반영이 어렵습니다. 대신에 현재 출력 창에 가공 상황을 표현하고 있는데 좀더 자세히 표현하고 싶은 내용이 있으면 알려주시면 검토 후에 반영하도록 하겠습니다.
