### ISSUE TITLE
LOD1 가공 오류

### ISSUE THREAD

**Issue by cheon-saeyeong** [EgisCorp/XDWORLD-Builder-Professional#53]
XDWORLD-Builder-Professional v_5.1.1 버전 활용하여 LOD1 건물 타일링 결과
불특정하게 건물 옆면, 지붕면이 정상적으로 가시화가 되지 않는 오류 발생(로컬 빌더에서 확인)
![image](https://github.com/EgisCorp/XDWORLD-Builder-Professional/assets/145958340/d5b4d214-8040-4194-a263-da03c4d41af9)

**Comment by egiskorea-ryong** [comment]
안녕하세요.

해당 오류 수정되어 v_5.1.1 버전으로 재배포 되었습니다.

감사합니다.

![Uploading mail002A30.png…]()
