### ISSUE TITLE
v_5.1.5버전 오류

### ISSUE THREAD

**Issue by KimSunYoungyoung** [EgisCorp/XDWORLD-Builder-Professional#54]
브이월드-3ds-시작(번개모양)을 클릭했을시
1. 삭제, 영역으로 이동 불가능
![a](https://github.com/user-attachments/assets/24821c65-8247-4606-b99e-407ba9f1c056)

2. 생성폴더와 가공폴더단위에 올바른 파일을 넣은 후 시작 버튼을 눌렀을 때 전 버전처럼 가까이 줌인되지않음

3.  마우스휠을 누른 후 떼어도 눌렀을 때와 같은 기능이 나타남

**Comment by egiskorea-ryong** [comment]
안녕하세요. 

* 3ds 가공에서 가공 완료 후 카메라 이동 불가
* 레이어 목록에서 "영역으로 이동" 시 이동 불가

위 2가지 사항에 대해 5.1.5버전 테스트 결과 정상 동작하는것을 확인했습니다.

사용하신 데이터를 첨부해주시면 자세히 확인해보겠습니다.
