### ISSUE TITLE
v5.1.5 지형 및 영상 가공 오류

### ISSUE THREAD

**Issue by cheon-saeyeong** [EgisCorp/XDWORLD-Builder-Professional#58]
![image](https://github.com/user-attachments/assets/6b96ef93-2c15-4304-baf3-699cd7321af7)

**Comment by egiskorea** [comment]
1. 지형
 - 4326외 다른 좌표계 가공시 오류나는 것을 수정하였습니다.
 - 샘플로 주신 5186으로 지형 가공하여 가시화되는 거 까지 확인하였습니다.
 - 5186 지형데이터를 가공한 결과입니다.
![20240809_102553_139](https://github.com/user-attachments/assets/427f1ce2-09d6-4531-ba19-45cdf44e9506)

2. 영상
 - meta 데이터가 있는 경우는 폴더를 던져 넣으면 레이어 가시화 됩니다.
 - meta 데이터가 없는 이전에 만들어진 경우에 대해서는 추가로 작업 중이고 완료되면 본 내용을 갱신하겠습니다.
