### ISSUE TITLE
v5.1.5 3DS 및 OBJ 텍스쳐 품질 저하

### ISSUE THREAD

**Issue by cheon-saeyeong** [EgisCorp/XDWORLD-Builder-Professional#59]
![image](https://github.com/user-attachments/assets/0adf52bc-e8e6-4a00-bea0-36716ab2d10d)

**Comment by egiskorea-ryong** [comment]
안녕하세요.

수정 후 보내주신 샘플 데이터로 확인결과 정상 동작하는것을 확인하였습니다.

배포시 해당 내용 추가하여 배포하겠습니다.

감사합니다.
