### ISSUE TITLE
v5.1.5 가공 현황 로그 오류

### ISSUE THREAD

**Issue by cheon-saeyeong** [EgisCorp/XDWORLD-Builder-Professional#64]
![image](https://github.com/user-attachments/assets/06b6a248-594f-4fae-b4e9-a13c9c7aa890)

**Comment by egiskorea** [comment]
이전 버전에서는 레벨별 가공 메세지를 표현하였는데 현재 버전을 방식을 변경했습니다. 
가공 대상에 따라서 진행 현황 메세지는 다양하게 나오는데 가공 완료  예산 시간이나 가공 현황은 충분히 가늠할 수 있습니다.
아래는 영상 가공시 나오는 메세지 입니다.
![남는시간](https://github.com/user-attachments/assets/16952d95-5506-43af-b8aa-36f7d37b0a0f)
아래는 지형 가공시 나오는 메세지 입니다.
![남는시간2](https://github.com/user-attachments/assets/0bbc670d-fe1c-48b9-bf3b-95eb46be575d)
