### ISSUE TITLE
v5.1.5 지형 차이

### ISSUE THREAD

**Issue by KimSunYoungyoung** [EgisCorp/XDWORLD-Builder-Professional#65]
댐,하천 물관리 플랫폼(http://58.123.178.38:16808/dt3d/portal.do)과 xd월드의 지도와 동일하지 않습니다.
어떻게 해야 xd월드에서 해당 플랫폼과 같은 지형을 쓸 수 있을까요?
사진은 용담댐 입니다
![깃허브 xd](https://github.com/user-attachments/assets/02721cf7-d6e2-4be3-a1f4-f8d6251d58e5)
![깃허브 플랫폼](https://github.com/user-attachments/assets/0c6f63de-f90b-4a81-a601-f00e4c510a8a)

**Comment by YangHeeBong** [comment]
확인 결과 댐.하천 물관리 플랫폼은 자체적으로 제작한 지형 영상 데이터로 확인 하였습니다.

웹 플랫폼 개발자에게 이지스 dt 플랫폼에서 사용 중인 지형 영상 데이터 요청 방식으로 변경하시면 됩니다.

**Comment by plusvolts** [comment]
안녕하세요 양희봉 차장님. 김상민 차장입니다. 혹시 빌더에 외부 XDServer에 배포되어 있는 DEM을 가져올 수 있는 기능이 있는지 궁금합니다. 브이월드와 샘플지도는 목록에 있는데 사용자 지도는 폴더로만 되어 있어서 없다면 URL로 가져올 수 있는 기능이 있으면 좋을 것 같은데 기능 추가가 가능한지도 문의드립니다.

**Comment by YangHeeBong** [comment]
현재는 관련 기능은 존재하지 않지만 다음주 화요일 까지 web 엔진 처럼 서버 정보를 입력 후 지도 변경이 가능하도록 지원하겠습니다.

**Comment by YangHeeBong** [comment]
## UI

![image](https://github.com/user-attachments/assets/eb45af93-6e64-46fa-88c1-8513a492df8f)

### 난독화: 지형 데이터 암호화 여부
### 사용자 지정(Local) 지도 설정: 로컬 경로에 있는 지형 및 영상 경로 설정
### 사용자 지정(Server) 지도 설정: XDServer로 구성된 Web Server 요청 설정

### 난독화
지형 정보 유출 방지를 위해 지형 파일(.bil)에 난독화 작업이 진행된 경우가 존재하고 이런 난독화된 지형 파일은 복호화를 작업을 통해 정상적인 지형 형상 가시화가 가능합니다.
이 옵션을 통해 난독화 된 파일(.bil)은 True로 설정, 난독화 되지 않은 파일(.bil)은 False로 설정 해야합니다.
만약 난독화된 bil 파일을 복호화하지 않은 경우, 아래와 같은 결과를 확인할 수 있습니다.

![image](https://github.com/user-attachments/assets/47124975-d45f-419b-805e-dbafa726eca9)

### 사용자 지정(Local) 지도 설정
이 옵션은 현재 디바이스 내부에 있는 지형 및 영상 경로를 통해 지도를 가시화하는 기능입니다. 지형과 영상이 한 세트로 구성되어 있어야 합니다.

### 사용자 지정(Server) 지도 설정
이 기능은 Web Server를 통해 데이터를 요청하는 것으로, XDServer로 구성된 요청만 처리할 수 있습니다.

아래 그림은 샌드박스에서 사용한 지도 데이터를 생성한 후 가시화된 화면입니다.
![image](https://github.com/user-attachments/assets/f4e319c0-5ac3-425b-9ebc-0064997f4059)

1번은 샌드박스에서 사용하는 지도 서버 정보입니다.
2번은 지도 적용 완료 후 나타난 로그입니다.

이를 통해 정상적으로 지도를 받아오는 것을 확인할 수 있습니다.

### 추가 기능 설명
기능을 개발하는 과정에서 다음과 같은 추가 사항이 필요하다고 판단하여 아래 기능을 만들었습니다:

1. 입력된 정보로 구성된 URL 확인
2. 서버 응답에 따른 지도 적용

1번 항목은 입력된 정보로 URL이 정상적으로 생성되었는지 확인하기 위한 기능입니다. 지도 변경 작업 시, 아래와 같은 메시지 박스가 출력됩니다.

![image](https://github.com/user-attachments/assets/a28d26c8-6f0e-4c50-8485-af35112dae31)

구성된 URL이 올바르다면 확인 버튼을 누르고, 그렇지 않다면 취소 버튼을 누른 후 Server 요청 옵션을 수정해 주시기 바랍니다.

2번 항목은 URL이 정상적으로 구성되었더라도, 서버에서 응답이 없거나 입력에 오타가 있을 경우 문제가 발생할 수 있는 상황을 방지하기 위한 기능입니다. 서버에 데이터를 요청한 후, 요청된 데이터가 존재한다면 지도를 적용하고, 그렇지 않다면 아래와 같은 메시지 박스를 출력합니다.

![image](https://github.com/user-attachments/assets/295dbbb5-f379-4080-9469-da8e60f4d204)

이 메시지 박스를 통해 서버에 데이터 응답이 없거나 잘못된 서버 요청임을 확인할 수 있으며, Server 요청 옵션을 수정해 주시기 바랍니다.

## 현재 이 기능이 첨부된 빌더는 2024년 8월13일 15시 전후로 릴리즈 업데이트 예정입니다.

**Comment by plusvolts** [comment]
신규 기능 테스트 해보는데 연결이 위에 2번 이미지 같은 오류가 발생하는데 혹시 tile 레이어에 대한 확장자 제한이 있는지 궁금합니다. jpg tile인데 계속 오류가 발생해서 입력한 파라미터 보고 확인 한번 부탁드리겠습니다.
![스크린샷 2024-07-31 075709](https://github.com/user-attachments/assets/c91f858b-1238-4faf-9df0-aa24d72c9c3e)
![스크린샷 2024-08-13 165019](https://github.com/user-attachments/assets/6be654c6-0452-40ca-b480-590dd3872101)

**Comment by YangHeeBong** [comment]
현재 몇가지 소스 수정 후 아래와 같이 지형, 영상 요청 완료 하였습니다.

![image](https://github.com/user-attachments/assets/db94a03a-65e5-4147-8658-f20fcaa75f16)

원인 확인 결과 입력 url을 보안상 문제 해결을 위해 http를 https와 포트 사용에 대한 제한 부분이 존재하였습니다. 

이부분에 대해서 네트워크 관련 부분을 개발하신분과 상의 후 오늘 중으로 처리 해서 업데이트 하겠습니다.

**Comment by YangHeeBong** [comment]
이 이슈는 5.1.7 빌더 프로에 처리 되었습니다.

삭제 부분은 추후 진행하도록 하겠습니다.

**Comment by plusvolts** [comment]
5.1.7 다운받아서 동일하게 입력하였는데 지도 로딩에 대한 메시지나 지도 표출 없고 지도 패널 쪽에서 마우스 클릭하면 빌더가 다운되네요. (입력 후 번개 버튼 눌렀습니다) / 키는 어짜피 체크 안하지만 변경해보고 dem 부분도 true, false 로 변경해서 해보긴 했는데 같은 증상을 보입니다.

![제목 없음](https://github.com/user-attachments/assets/dc5cc54a-e168-416f-bc84-d62d91741530)

**Comment by YangHeeBong** [comment]
원인 확인 결과 dem 레이어(dem_all_korea_dam_5m) 호출에서 문제가 있는걸 확인 하였습니다. 

![image](https://github.com/user-attachments/assets/bbd1042a-b787-4b30-b265-97259b3a12cb)

현재 지형 영상 요청 테스트는 영상만 체크 하였습니다만. 이 문제 확인 후 영상 체크 후 지형 체크 모듈을 추가 하였습니다. 

요청 실패 시 붉은 박스 항목을 통해 지형 문제인지 영상 문제 인지 확인 가능하다록 작성하였습니다.

![image](https://github.com/user-attachments/assets/bf263087-4b87-41a9-a114-fc2a6221a152)

10시 전 후 빌더 프로 릴리즈 업데이트 없이 5.1.7로 업데이트 하겠습니다.
