### ISSUE TITLE
지형 읽기 오류

### ISSUE THREAD

**Issue by KimSunYoungyoung** [EgisCorp/XDWORLD-Builder-Professional#66]
지도연결-사용자지도-지형폴더에 저희 서비스에 활용중인 DEM 폴더를 지정하고 적용을 눌렀더니 다운 됩니다. 사용자 지도 기능에 대한 검토 부탁드립니다.

**Comment by YangHeeBong** [comment]
https://github.com/user-attachments/assets/fa59387d-c85b-4329-a197-b1181c181772

기능 테스트 정상적으로 동작하는걸 확인 하였습니다.

하지만 단일 변경(지형만, 영상만)시 오류가 발생하는 경우를 확인 하였습니다. 

혹시 단일 변경하셨나요??? 

추후 예외처리를 통해 가능/불가능에 대한 메시지 처리 등록을 하겠습니다.

**Comment by YangHeeBong** [comment]
![image](https://github.com/user-attachments/assets/881f4af8-c905-45e2-a733-f51870394d7b)
영상, 지형에 경로 설정이 되어야 지도 변경이 되도록 예외처리를 하였습니다.

현재 영상과 지형이 같이 설정되어야하는 이유는 아래와 같습니다.

1. 영상과 지형은 하나의 데이터 셋으로 구성.
2. 지도 변경 시 영상, 지형 데이터 셋은 동시에 삭제
3. 입력된 새로운 지도 정보로 지도 데이터 셋을 재 설정

즉 지형, 영상 경로가 하나만 설정 시 데이터 셋 구성이 되지 않으므로 오류가 발생합니다.

**Comment by plusvolts** [comment]
네 해당 부분 영상은 너무 커서 로컬 보유가 안되서 지형만 로딩 하였던 경우에 다운됐던 현상입니다.
