### ISSUE TITLE
v5.1.5 텍스쳐

### ISSUE THREAD

**Issue by KimSunYoungyoung** [EgisCorp/XDWORLD-Builder-Professional#68]
![color_v2](https://github.com/user-attachments/assets/8b3b8230-b8c6-434b-a77f-841e2083797e)

해당 텍스쳐를 사용할 때 너무 멀거나 가까이 보면 텍스쳐가 깨져보입니다
다만 회색(무채색)은 잘 보입니다.
![멀](https://github.com/user-attachments/assets/d8443dc4-7702-4f67-b4aa-fcb105d2524d)
![중간](https://github.com/user-attachments/assets/a25bd033-61d8-48fb-a38f-069fbd6d22d7)
![가까움](https://github.com/user-attachments/assets/742b7c19-dd7b-4c58-ae12-7247f9b2f57c)

**Comment by egiskorea-ryong** [comment]
안녕하세요.

해당 내용 확인하여 오류 수정하였습니다.

오늘 오후에 배포시 해당 내용 포함하여 배포하겠습니다.

감사합니다.
