### ISSUE TITLE
v5.1.6. 체크박스

### ISSUE THREAD

**Issue by KimSunYoungyoung** [EgisCorp/XDWORLD-Builder-Professional#69]
![캡처](https://github.com/user-attachments/assets/4840f9df-db4d-400a-924a-f3340578e497)
![캡처02](https://github.com/user-attachments/assets/aeddf004-293f-4972-95df-3e613d751f97)
체크박스를 해제해도 오브젝트가 사라지지않습니다
또한 삭제를 눌러도 삭제되지않으며 반복해 실행하면 xd빌더가 종료됩니다

**Comment by YangHeeBong** [comment]
네 확인 완료했습니다. 

오늘 릴리즈 업데이트에 레이어 visible 기능 처리 후 올리겠습니다. 

또한 삭제 부분은 추후 테스트 후 기능 수정하겠습니다.

**Comment by YangHeeBong** [comment]
이 이슈는 5.1.7 빌더 프로에 처리 되었습니다.

삭제 부분은 추후 진행하도록 하겠습니다.
