### ISSUE TITLE
poi 생성 시 최대레벨 최소레벨 지정 관련 문의

### ISSUE THREAD

**Issue by yoonmiegis** [EgisCorp/XDWORLD-Builder-Professional#70]
poi 생성을 위해 최대레벨과 최소레벨을 지정하였으나 반영되지 않아 문의드립니다.
이미지에는 숫자로 있지만, 숫자로도 작업하고, 컬럼명(s_level, e_level)으로도 넣어서도 시도해보았습니다.
또한, 가공 작업 후 오류 메시지도 발생하여 첨부합니다.

![2024-08-14 14 04 33](https://github.com/user-attachments/assets/00cc836b-b6ed-4010-8899-898a0cd10fd1)
![2024-08-14 14 08 41](https://github.com/user-attachments/assets/e407710c-4939-4604-b043-6b621fbc8b69)
![2024-08-21 11 09 36](https://github.com/user-attachments/assets/539e943a-29db-4008-bc12-c0994b09b081)

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해 답변드리겠습니다.

질문하신 두 가지 사항에 대해 설명드리겠습니다.

### 1. 레벨별 가시화

가시화 엔진에서 기존 모듈을 수정한 결과, 아래와 같은 결과를 확인했습니다. 동일한 위치에서 POI 변경 시 발생하는 화면의 결과입니다.

https://github.com/user-attachments/assets/b1f758c8-216f-4f45-88cf-5d9b985c6369

DBF 파일을 참조하여 아래와 같은 s_level과 e_level을 확인했습니다.

![image](https://github.com/user-attachments/assets/5300417b-7b6c-4e3d-8409-1ec6c3f99ff9)

### 2. 오류 메시지 발생

발생한 오류 메시지는 현재 가시화된 레이어와 연동되는 image.map 파일이 없다는 의미입니다. 만약 image.map 파일이 정상적으로 존재한다면 이 메시지는 발생하지 않습니다. 이번 릴리즈 버전에서는 이 메시지를 Error가 아닌 Warning으로 수정하겠습니다.

질문에 대한 답변은 위와 같습니다. 그러나 질문을 처리하는 과정에서 몇 가지 테스트를 하던 중 오류라고 하기에는 애매한 문제가 발생하여 아래와 같이 정리했습니다.

1. POI 중복 레벨
2. e_level 공백

이 두 가지 문제입니다.

### 1. POI 중복 레벨
첫 번째 이미지에서 제주도 항목의 ID(198654)가 s_level ~ e_level 5~9를 포함하고 있는데, ID(187718, 187853)에서도 중복으로 POI가 생성되는 부분이 있습니다. 
첫 번째 이미지의 제주시 항목에서도 8, 9, 10의 세 가지 레벨에서 각각 POI가 생성되는 부분이 존재합니다. 이 부분이 정리된다면 POI 중복 현상을 많이 개선할 수 있을 것으로 보입니다.

### 2. e_level 공백
e_level 입력값이 공백으로 가시화 최종 레벨 설정 문제도 있습니다. 현재 가시화에서 시작 가시화 레벨보다 끝 가시화 레벨이 작다면, 시작 가시화 레벨에 1을 더한 값으로 끝 가시화 레벨을 설정하여 정상적으로 가시화되도록 처리했습니다.

![image](https://github.com/user-attachments/assets/2e9a27e1-c717-48a5-bef9-33cc22d68987)

**Comment by YangHeeBong** [comment]
v_5.1.8 빌더 설치본에서 제공합니다.
