### ISSUE TITLE
3d poi 가시화 방법 수정 요청

### ISSUE THREAD

**Issue by yoonmiegis** [EgisCorp/XDWORLD-Builder-Professional#71]
XDBuilder에서 3d poi 가공 후 시각화 할 때, 묶음으로 호출할 수 있도록 수정이 가능할까요?
현재 건마다 호출하다보니 출력에 시간이 너무 많이 소요됩니다. 
첨부한 1번 이미지는 2분, 2번 이미지 기준 완벽하게 나오기까지 3분 걸렸습니다. 
![2024-09-12 11 20 23](https://github.com/user-attachments/assets/f5019851-c4e9-4c59-b0b3-bbef30353584)
![2024-09-12 11 07 10](https://github.com/user-attachments/assets/0c5595d9-eb50-4a75-9ce5-336c8a13df45)

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해 답변드리겠습니다.

POI 묶음 처리 부분은, 혹시 POI 데이터를 한 번에 처리해서 가시화하기를 원하시는 것 같습니다.

그렇다면, POI 가공 시 생성 레벨을 기본 15레벨이 아닌 더 작은 범위로 처리하시면 될 것 같습니다.

![image](https://github.com/user-attachments/assets/d4eca0dc-f39a-4ea4-901a-a2792f39c372)

그 이유는 아래 그림으로 설명드리겠습니다.

![image](https://github.com/user-attachments/assets/dcc113e5-4770-46c3-9f28-ef28e3f3ff92)

저희는 기본적으로 타일(Tile)을 기준으로 지구본을 나누어 처리 중입니다. 15레벨 타일 4개 묶음이 14레벨이며, 14레벨 타일 4개 묶음이 13레벨입니다.

**Comment by yoonmiegis** [comment]
가공 레벨은 15로 유지해야 합니다.
영역(블럭 또는 행정구역 등) 별 묶음으로 호출하도록 수정이 가능한지가 궁금합니다.

**Comment by YangHeeBong** [comment]
일단 가공 레벨 15를 유지해야하는 이유는 무엇인가요??

XDWorld 엔진에서 생성한 Tile 레이어 구성 요소 중 "[lod_object_detail_ratio](https://egiscorp.gitbook.io/xdworld-webgl-manual/introduce-1/layer/jslayer)"을 통해 가시화 거리를 변경할 수 있습니다.

만약 14레벨로 가공 후 lod_object_detail_ratio 값을 1보다 작은 값으로 처리 하신다면 15레벨에서 가시화 되는 효과를 가질 수 있습니다.

"영역(블럭 또는 행정구역 등) 별 묶음" 부분에 대해서는 빌더에서 단순히 데이터를 만드는 부분이 아니라 요청하는 Server 부분
이 변경이 필요하면 XDServer를 통해서 처리가 불가능합니다. 만약 처리한다고 한다면 Web 개발 부분에서 해당 영역에 대한 데이터 요청 후 POI 생성 부분이 필요할것 같습니다.
