### ISSUE TITLE
v_5.1.9 전체삭제

### ISSUE THREAD

**Issue by KimSunYoungyoung** [EgisCorp/XDWORLD-Builder-Professional#72]
사용자지도-3ds를 사용한 후 shift를 이용해 전체선택 후 한번에 삭제하는것이 불가능합니다
![캡처](https://github.com/user-attachments/assets/5386dacc-3216-4c7a-a71e-dcb69000b5be)

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해 답변드리겠습니다.

확인 결과 다중 삭제에 대한 처리 부분이 없는걸로 확인 하여 다음주 이슈 문제를 해결한 새로운 릴리즈 설치 버전을 공유 하겠습니다.

**Comment by YangHeeBong** [comment]
결과

https://github.com/user-attachments/assets/1ccdc314-aac3-4df0-8e41-d89d01d02338

이 기능이 적용된 릴리즈 설치본은 5.1.10에서 제공합니다.

5.1.10은 금주 목요일 업데이트 예정입니다.

**Comment by YangHeeBong** [comment]
5.1.10 설치본에서 이슈에 대한 문제를 해결 가능합니다.
