### ISSUE TITLE
3d poi 텍스트 없이 이미지만 출력하도록 가공 불가능

### ISSUE THREAD

**Issue by yoonmiegis** [EgisCorp/XDWORLD-Builder-Professional#73]
3d poi 가공할 때에 이미지는 있으나 텍스트가 없는 경우가 있습니다.
v5.1.8 버전에서 텍스트가 없으면(해당 컬럼값이 NULL), 이미지도 출력되지 않습니다. 

텍스트 없이 이미지만 출력하는 경우, 이미지 없이 텍스트만 출력하는 경우 모두 필요합니다. 
확인 부탁드립니다.

대상 shape 파일은 따로 전달드리겠습니다.

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해 답변드리겠습니다.

관련 기능을 수정하여 아래와 같은 결과를 확인 하였습니다. 

![image](https://github.com/user-attachments/assets/9099c1e7-de76-429f-b0d9-3886bea8d030)

현재 이슈에 대한 문제점을 해결하기 위해 소스를 수정하면서 Web Engine과 Builder 가공 소스 일부도 함께 수정되었습니다.

Builder 가공 소스는 새로운 설치본을 통해 POI 데이터를 재가공하면 해결할 수 있지만, 가공된 Tile Layer 기반 POI 데이터가 가시화될 때 화면에 출력되지 않는 부분이 있어 함께 수정하였습니다.

현재 심볼만 존재하는 Tile Layer 기반 POI는 Web Engine에서 사용할 수 없으나, 이번 주에 업데이트되는 Web Engine을 통해 정상적으로 가시화할 수 있도록 하겠습니다.

**Comment by YangHeeBong** [comment]
5.1.10 설치본에서 이슈에 대한 문제를 해결 가능합니다.
