### ISSUE TITLE
V5_5.1.10 사용자지도

### ISSUE THREAD

**Issue by KimSunYoungyoung** [EgisCorp/XDWORLD-Builder-Professional#74]
사용자지도에 저장기능을 요청합니다

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해 답변드리겠습니다.

사용자 지도 저장 기능은 현재 존재하고 있습니다.

![image](https://github.com/user-attachments/assets/0c5a0f29-19e8-4e36-bfb4-279c21ec6f88)
현재 이미지에서 레이어 3개가 존재하고 붉은 색 저장 항목을 누르면 파일을 저장할수 있는 UI 컨트롤이 나옵니다.

이를 통해서 "명칭".XDW 파일을 생성할 수있으면 이 파일을 아래 그림과 같이 열기 또는 드래그앤 드랍을 통해 저장한 사용자 지도를 불러올수 있습니다.

![image](https://github.com/user-attachments/assets/932e7f9a-888e-4833-8283-b984840ae1d8)

이떄 주의할점은 XDW 파일은 사용자 지도에 등록된 레이어 데이터 자체가 저장된 것이 아닌 경로 만 저장된 JSON 파일 구조입니다. 만약 xdw 저장 후 실제 레이어 데이터가 저장된 경로에 데이터를 삭제한다면 xdw를 정상적으로 동작하지 않습니다.
