### ISSUE TITLE
V5_5.1.10 3ds가공

### ISSUE THREAD

**Issue by KimSunYoungyoung** [EgisCorp/XDWORLD-Builder-Professional#75]
3ds가공 후 사용자 지도의 오브젝트들의 이름수정 기능을 요구합니다(현 기능 : 영역으로이동, 삭제, 속성테이블)
)

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해 답변드리겠습니다.

질문의 요지를 정확히 파악하지 못했습니다.

사용자 지도의 오브젝트라는 것이 무엇을 의미하는지, 그리고 이름 수정 기능을 요구한다는 것이 어떤 의미인지 명확하지 않습니다.

또한,  질문에 나온 "현 기능"을 보면 사용자 레이어를 선택한 후 오른쪽 마우스를 클릭했을 때 나타나는 메뉴 항목에 대한 이야기인 것 같은데, 질문의 의도를 전혀 파악하지 못하고 있습니다.

제가 가지고 있는 3ds 파일 가공된 데이터를 빌더에 업로드하여 가시화한 결과와 이름 수정 기능과는 관련된 부분이 없으니, 질문을 좀 더 구체적으로 설명해 주시기 바랍니다.

**Comment by YangHeeBong** [comment]
혹시 사용자 지도에 등록된 사용자 레이어의 이름 변경을 원하시는건가요??
