### ISSUE TITLE
V5_5.1.10 삭제기능

### ISSUE THREAD

**Issue by KimSunYoungyoung** [EgisCorp/XDWORLD-Builder-Professional#76]
오브젝트들을 삭제할 때 다른 오브젝트들의 체크박스가 전부 체크되는 현상 발생(그렇지만 지도에 나타나지는 않음)
여러 오브젝트들을 한번에 삭제할 때 바로 삭제되지않고 체크박스가 표시된뒤 한번 더 삭제하여야 삭제기능이 유효함

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해 답변드리겠습니다.

오브젝트 삭제라는게 사용자 지도를 구성하는 사용자 레이어를 뜻하는 건가요?

현재 기능 테스트 결과 질문과 같은 문제점이 발생하는 것 같습니다. 

관련 내용을 확인 후 수정 하도록 하겠습니다.

**Comment by YangHeeBong** [comment]
5.1.11 설치본에서 배포 예정입니다.
