### ISSUE TITLE
3D POI 가공 시 심볼에 텍스트 삽입 가능 기능 요청 

### ISSUE THREAD

**Issue by yoonmiegis** [EgisCorp/XDWORLD-Builder-Professional#77]
3D POI 가공 작업을 하다보니, 
고속도로, 국도, 지방도 등과 같이 심볼에 숫자나 글자를 입혀서 출력 해야하는 경우가 있습니다. 
(첨부한 이미지 참고)

국내의 경우 한정적이다보니 이미지를 만들어서 반영할 수 있습니다.
하지만, 추후 세계지도 또한 3D POI로 가공할 계획을 가지고 있습니다. 
 
심볼에 텍스트 삽입하는 기능에 대해
개발 여부 긍정적으로 검토 부탁드립니다.

![2024-09-30 15 40 33](https://github.com/user-attachments/assets/fc80287f-ba40-4c9e-959b-b6eb91be13f7)
![2024-09-30 15 40 39](https://github.com/user-attachments/assets/bd36762e-94dd-4054-9a69-2a10300df4f1)
![2024-09-30 15 41 02](https://github.com/user-attachments/assets/4e2ff64d-2670-4881-9f78-d62289c76d00)

**Comment by YangHeeBong** [comment]
안녕하세요. 현재 이슈에 대해 답변드리겠습니다.

지금 이야기하신 부분은 단순하게 보기 어려운 기능 같습니다. 

고려해야할 상황이 몇가지가 있을것 같습니다.

1. 출력할 텍스트 폰트 크기는 심볼 이미지의 실제 크기에 따라 개별처리 필요
  - 1, 2, 3번 심볼 이미지는 다를 경우 텍스트 폰트 크기를 어떻게 설정할것인가?
2. 출력할 텍스트 폰트는 입력된 심볼 이미지 배경색에 따라 개별 색상값을 가져야한다.
3. 출력할 텍스트 가로 또는 세로 길이가 심볼이미지를 초과한 경우 어떻게 표현할것인가?
4. 텍스트를 단순히 심볼 이미지 중심으로 설정할 것인가?
 - 3번 이미지 인경우 중심 값으로 설정 시  정상적으로 처리가 안됨
5. poi 개수만큼 심볼이미지를 생성하는 과정이 필요함으로 가공 시간이 필요

단순히 텍스트를 넣는 부분으로 처리하기에는 예외처리와 고려해야할 상황이 많이 있는것 같습니다.

POI 별 개별 설정을 통해 생성하는 방안으로 들어간다면 너무 많은 설정이 들어가고 그게 아니라면 단순히 지금과 같이 미리 만들어진 POI 심볼 데이터와 shape 파일과 연동하는 방안이 더 효율적으로 보입니다

다른 방안이라면 고정된 심볼 이미지, 크기, 배경색상을 통해 중심을 기준으로 제한된 TEXT를 입력하는 방안이 존재하지만 이 방식을 통한다면 POI 심볼이미지를 다양하게 사용에 어려울것 같습니다.

**Comment by yoonmiegis** [comment]
답변 감사합니다. 현재 지방도의 경우 300개 이상의 이미지가 필요합니다. 이에 해당 건이 가능한지 문의드렸습니다.
이미지로 생성해서 가공하도록 진행해보겠습니다. 

추가적으로 문의드리고 싶은 것은 이미지를 기준으로 텍스트의 위치를 선택할 수 있도록 수정은 가능할까요?
현재는 이미지 아래에 텍스트가 위치합니다만, **텍스트를 이미지 위쪽**으로도 가공이 가능하도록 개발이 가능하실까요? 
(예)
1. 텍스트
    이미지

**Comment by YangHeeBong** [comment]
네 말씀대로 심볼 이미지와 텍스트 문자열 이미지를 위치를 조정하는 형태가 더 좋아보입니다.

하지만 이부분도 기존에 가지고 있던 다양한 POI 심볼이미지에 따른 폰트크기, 색상, 위치 3가지 이상 입력값이 존재 해야하며

이 정보는 빌더에서 레코드별 정보 수집하기에는 효율적이지 못하기 떄문에 Shape 생성 과정에서 3가지 옵션에 대한 정보가 필요 할것 같습니다. 

말씀하신대로 한 경우 아래와같은 결과를 얻을수 있습니다.

![image](https://github.com/user-attachments/assets/43acd967-fe34-4a8e-87da-28df949c839a)

만약 전체 가공전 심볼이미지와 텍스트 이미지 위치 테스트가 필요하다면 현재 Web Engine에서 제공하는 

JSPoint 클래스 구성 API인 "setTextMargin"을 통해 텍스트 위치 이동이 가능합니다.

**Comment by yoonmiegis** [comment]
Shape 생성 시 옵션으로 넣어서 반영이 가능하다면 매우 좋을 듯 합니다!
방향 선택(위, 아래, 왼쪽, 오른쪽 등 4개 코드 중 선택), 위치 지정(숫자), 폰트 종류나 크기, 색깔 등도 모두 넣어서 가공할 수 있다면 아주 획기적으로 개선될 것 같습니다. 
Shape 파일 생성 시 필요한 컬럼명 등 말씀해 주시면 반영하겠습니다.

**Comment by yoonmiegis** [comment]
그리고 아래처럼 이미지와 텍스트가 너무 붙었다는 의견이 있어 겹치지 않게 먼저 반영해주실 수 있을까요?

![2024-10-07 14 22 58](https://github.com/user-attachments/assets/adde2287-c5c7-4529-b3fa-e401e9c3b6cc)

**Comment by YangHeeBong** [comment]
일단 1차적으로 답변드리겠습니다.

POI 하나의 문자와 하나의 심볼 이미지를 병합해서 시각화하는 오브젝트로 요청하신 기능은, 
심볼 이미지에서 문자를 표현할 입력 좌표(dbf 컬럼 x, y 또는 Margin X, Margin Y 등)를 가진 컬럼을 선택한 후 해당 위치에 POI를 구성하고, 하나의 문자를 해당 위치에 표현하여 심볼 이미지 안에 존재하는 하나의 문자 정보를 시각화하는 기능으로 판단됩니다.

필요한 정보로는 기존 기능에 추가하여 [답변](https://github.com/EgisCorp/XDWORLD-Builder-Professional/issues/77#issuecomment-2387536886)에서 언급한 대로 좌표 값에 대한 2개의 컬럼을 통해 처리할 수 있을 것으로 보입니다. 해당 위치는 `setTextMargin`으로 입력된 값으로 등록하시면 문제가 없을 것으로 예상됩니다.

이 기능을 기준으로 개발하도록 하겠습니다.

또한 [질문](https://github.com/EgisCorp/XDWORLD-Builder-Professional/issues/77#issuecomment-2395937772)에서 이미지와 텍스트가 겹쳐지는 부분에 대해 언급하셨습니다.

몇 가지 질문 사항이 있습니다:
1. 질문하신 POI는 Tile Layer로 시각화한 POI인가요? 아니면 UserLayer로 생성한 POI인가요?
2. Tile Layer POI라면 가공은 Builder Pro 5.0 이상에서 하신 건가요?
3. Tile Layer POI라면 가공 이미지와 글꼴 사이즈는 어떻게 되나요?

현재 문자 이미지 시각화 좌표는 심볼 이미지 크기와 문자에 적용된 폰트 크기를 연산하여 출력하는 중입니다. 하지만 작은 심볼 이미지에 비해 큰 폰트가 입력된 경우 다음과 같은 현상이 발생하는 것 같습니다.

이 부분에 대한 더 구체적인 정보가 필요할 것 같습니다. 단순히 심볼 이미지와 문자 사이의 공간을 늘릴 경우, 기존에 정상적으로 출력되던 POI에서 심볼 이미지와 문자 사이의 공간이 너무 커질 수 있는 문제가 발생할 수 있습니다.

**Comment by YangHeeBong** [comment]
5.1.12 설치본에서 배포 예정입니다.

**Comment by YangHeeBong** [comment]
![image](https://github.com/user-attachments/assets/f48d6e1e-029b-4637-860e-e56388b7ef05)

Margin 관련하여 UI가 추가되었습니다.

기본적으로 미사용 시 Margin 값은 0,0으로 입력됩니다.

UI 옵션은 두 가지로 정의됩니다.

- 입력
- 컬럼

입력 항목은 Shape 가공 시 모든 POI에 입력된 값이 일괄적으로 적용되며, setTextMargin 입력 시 나온 결과와 동일한 위치에 텍스트가 출력되도록 하였습니다.

컬럼 항목은 Shape를 구성하는 DBF 파일 내부에 존재하는 컬럼 항목으로, x와 y 각각의 기준값이 저장된 컬럼을 지정하여 가공 시 개별 POI마다 해당 레코드와 매칭된 값이 적용됩니다.
