### ISSUE TITLE
v5.1.10 지형 마이너스값 타일맵 가공 관련

### ISSUE THREAD

**Issue by cheon-saeyeong** [EgisCorp/XDWORLD-Builder-Professional#78]
물길 조석, 수위 등 시뮬레이션을 위한 마이너스 값 타일맵 가공 관련하여 기능개선 요청드립니다.

현재 지형 타일맵 가공 시 0 이상의 값만 가공이 가능한 상태로
마이너스 값 존재 시, 강제로 0으로 변경되어 가공됩니다.

마이너스 값 또한 지형이 패이는 형태로
타일맵 가공이 가능하도록 기능개선 요청드립니다.

검토 부탁드립니다.

**Comment by egiskorea** [comment]
요청하신 내용을 반영하여서 지형 가공 UI 상에서 마이너스 지형값을 사용할 것인지 무시할 것인지 옵션을 넣도록 하겠습니다.

**Comment by egiskorea** [comment]
안녕하세요.

마이너스 지형에 요청 사항은 다음과 같이 처리 되었습니다.
1. 가시화 모듈의 오류로 인해 이미 정상가공된 마이너스 지형이 제대로 보이지 않음
2. 가시화 모듈 수정 후 정상적으로 보임
3. 샘플 지역 위치(순천만 습지 갯골 마이너스 지형)
![aa0](https://github.com/user-attachments/assets/23afbff3-cbcf-43cb-b26e-bd4eca60604f)

4. 오목한 사각박스처럼 보이는 이유는 배경dem과 가공dem 간의 해상도 차이가 클수록 박스 깊이가 더 깊어짐
![aa2](https://github.com/user-attachments/assets/721b2faa-306d-432c-b2cf-52d75a48407b)

5. 갯골 바닥면 마이너스 지형 반영
![aa3](https://github.com/user-attachments/assets/be3e18b2-08aa-4c02-bdb9-3e62b513d660)


위와 같이 수정하였습니다. 다음 버전 릴리즈에 반영하겠습니다.

**Comment by YangHeeBong** [comment]
5.1.12 설치본에서 배포 예정입니다.
