### ISSUE TITLE
v5.1.10 새지도 열기 시 프로그램 셧다운

### ISSUE THREAD

**Issue by cheon-saeyeong** [EgisCorp/XDWORLD-Builder-Professional#80]
![image](https://github.com/user-attachments/assets/84ffb2d2-2502-469a-8366-0f67bc935fc4)

**Comment by YangHeeBong** [comment]
현재 기능 테스트 결과 프로그램 오류가 발생하는것을 확인 하여 관련 내용을 수정하였습니다. 

버전 5.1.11을 통해 오류 해결된 설치본을 첨부 하겠습니다.
