### ISSUE TITLE
v5.1.10 사용자지도 지형 타일맵 가시화 오류

### ISSUE THREAD

**Issue by cheon-saeyeong** [EgisCorp/XDWORLD-Builder-Professional#81]
![image](https://github.com/user-attachments/assets/3cb0ea27-9f1e-4c21-8f6d-0f9c296ac0fa)

**Comment by YangHeeBong** [comment]
현재 질문하신 정보로는 어떤 입력값으로 어떤 결과값이 출력되어야 하는지 판단하기가 힘듭니다.

몇가지 고려 사항이 있습니다.

1, 서버 또는 로컬 중 어디에서 요청한 데이터 인가?
2. 서버에서 요청한 데이터라면 데이터 요청 url이 어떻게 되는지 정보 공유가 필요합니다.
3. 로컬에서 요청한 데이터라면 지형, 영상 데이터가 필요합니다. (전체 데이터가 아니라도 0~11레벨 정도가 필요할것같습니다.)

그리고 질문하신 내용중 난독화 false, true 이미지가 같은 위치라고 한다면 동일한 이미지 결과를 얻어야하는데 현재 이미지도 다른 결과를 가지고 있는것 같습니다. 

좀더 상세한 정보를 부탁드립니다.

**Comment by YangHeeBong** [comment]
데이터 확인 후 현재 발생되는 부분은 기본지도 교체방식과 매쉬업 교체 방식 차이로 보입니다.

과거 빌더는 매쉬업 교체 방식을 통해 일부 지역만 지형 데이터를 교체하는 방식을 사용하였지만 현재는 지형 교체 방식으로 변경되었습니다. 

추후 빌더 업데이트를 통해 이부분을 처리 하도록 하겠습니다.
