### ISSUE TITLE
v5.1.10 3DS 및 OBJ 텍스쳐 품질 저하

### ISSUE THREAD

**Issue by cheon-saeyeong** [EgisCorp/XDWORLD-Builder-Professional#82]
![image](https://github.com/user-attachments/assets/f2f592b7-1726-4c54-b512-0ddde3901974)

**Comment by egiskorea-ryong** [comment]
안녕하세요.

과거 [이슈](https://github.com/EgisCorp/XDWORLD-Builder-Professional/issues/59)에서 답변한 내용과 동일합니다.

보내주신 샘플데이터로 가공시 현재도 정상 동작하는것을 확인할 수 있습니다.

예전에 문제가 되는 데이터가 아닌 다른 샘플을 보내주셨는데 

문제가 되는 데이터를 보내주시면 확인해보겠습니다.

**Comment by YangHeeBong** [comment]
5.1.11 설치본에서 배포 예정입니다.

**Comment by YangHeeBong** [comment]
5.1.12 설치본에서 배포 예정입니다.
