### ISSUE TITLE
v5.1.10 건물 타일맵 텍스쳐 레벨별 가시화 오류

### ISSUE THREAD

**Issue by cheon-saeyeong** [EgisCorp/XDWORLD-Builder-Professional#83]
![image](https://github.com/user-attachments/assets/39f42bbd-66c8-49da-a01b-b7e3d54c6283)

**Comment by YangHeeBong** [comment]
어떤 파일을 어떤 가공을 통해 시설물 데이터로 가공 하셨나요?

현재 이미지 결과만으로는 문제에 대한 해결에 어려움이 존재합니다. 

 가공 시 사용한 파일과 가공 옵션을 메일로 보내주시면 기능 테스트 해보겠습니다.

**Comment by YangHeeBong** [comment]
이 issues 83과 [issues 82](https://github.com/EgisCorp/XDWORLD-Builder-Professional/issues/82)와 비슷한 문제임을 확인 하였습니다.

issues 83 처럼 흰색으로 나오는 경우는 확인되지 않지만 LOD 텍스쳐에서 발생하는 문제를 확인 하였습니다. 

가공 결과에 대한 LOD 텍스쳐는 아래와 같이 정상적으로 출력되었습니다. 

![image](https://github.com/user-attachments/assets/749efbaf-d9cd-4cfb-be09-1a3954c34b0c)

LOD 텍스쳐 이미지 크기는 2048 * 2048 에서 512 * 512 까지 존재하는 걸 확인 하였고 가공과정에서는 문제가 없음을 확인 하였습니다. 

현재 문제는 가시화 시 매우 작은 시설물에 대해서 LOD 텍스쳐 요청이 안되는 부분을 확인하여 이부분을 수정하여 제공하겠습니다.

[issues 82](https://github.com/EgisCorp/XDWORLD-Builder-Professional/issues/82)과 issues 83 문제 해결은 

5.1.12 설치본에서 배포 예정입니다.
