### ISSUE TITLE
v5.1.10 LOD1 높이값 가시화 오류

### ISSUE THREAD

**Issue by cheon-saeyeong** [EgisCorp/XDWORLD-Builder-Professional#84]
![image](https://github.com/user-attachments/assets/ff434a95-d04c-47c0-a14a-e30cbadeccfd)

**Comment by YangHeeBong** [comment]
shape 파일을 이용한 LOD1 가공시 설정한 건물 높이(컬럼 bld_hght)가 재대로 적용이 안되다는 것 같습니다. 

관련 Shape 파일과 가공 시 사용한 옵션을 메일로 보내주시면 기능 테스트 해보겠습니다.

**Comment by egiskorea-ryong** [comment]
해당 오류 수정되었으며 다음 배포시 적용하여 배포하겠습니다.

감사합니다.

**Comment by YangHeeBong** [comment]
5.1.11 설치본에서 배포 예정입니다.
