### ISSUE TITLE
v5.1.11 포인트클라우드 가공 시 불특정한 높이 값 오류

### ISSUE THREAD

**Issue by cheon-saeyeong** [EgisCorp/XDWORLD-Builder-Professional#85]
포인트클라우드 가공 시 불특정하게 점군이 찢어진 형태로 높이 값에 오류 발생
(위) 원본 (아래) 가공 시 오류
![image](https://github.com/user-attachments/assets/0950bbce-600f-4d4a-8b26-f80bf990801b)

**Comment by YangHeeBong** [comment]
![image](https://github.com/user-attachments/assets/ab2f9641-3952-498e-9b54-b215436e3492)

현재 원인 파악 결과 포인트 클라우드를 구성하는 점군 데이터을 위치  x, y, z 변환 시 2바이트로 변환하는 부분이 있습니다.

이 부분은 전체적인 용량을 줄이기 위한 모듈로, 2바이트에서 표현 가능한 숫자를 벗어나 생기는 문제로 보입니다.

현재 4바이트 좌표계로 변환 시, 이미지와 같이 정상적으로 나오는 것을 확인하였습니다.
