### ISSUE TITLE
V5_5.1.12 3d 꺼짐문제

### ISSUE THREAD

**Issue by KimSunYoungyoung** [EgisCorp/XDWORLD-Builder-Professional#86]
사용자지도-지도연결-가공-3d-시작을 누른 후 오브젝트가 나타나기전에 빌더가 종료됨
11-13일오전에 해당현상 처음 발생하였고([v_5.1.8은 정상적으로 작동) 당일 9시 15분 쯤부터 해당문제가 다시반복됨(7시부터 그 전까지는 정상적으로 작동)
동영상은 아마란스로 제출하겠습니다

**Comment by YangHeeBong** [comment]
관련 문제를 확인하여 2024년11월 14일 오후 6시 XDWORLD_Builder_Professional_V5_5.1.12으로 재 업로드 하였습니다.
