### ISSUE TITLE
v5.1.12 포인트클라우드 타일맵 가공 오류

### ISSUE THREAD

**Issue by MinjiK00** [EgisCorp/XDWORLD-Builder-Professional#88]
안녕하세요.
포인트 클라우드 가공 시 한 차례 가공된 포인트 클라우드 타일맵에
생성폴더 경로 일치시켜 다른 포인트 클라우드 데이터를 가공할 경우
두 점군이 병합되지 않고 마지막 차례에 가공된 데이터만 존재합니다.
동일 생성폴더에 반복하여 점군 가공할 때 전체 데이터가 정상 가공될 수 있도록 수정 부탁드립니다.

**Comment by YangHeeBong** [comment]
포인트 클라우드는 가공은 현재 단일 가공만 지원하고 있습니다. 

포인트 클라우드는 단순히 데이터 병합으로 처리되지 않으면 내부적으로 연산 작업이 필요한 부분이 존재합니다. 

추후 병합이 가능하도록 지원 예정이지만 현재 바로 작업에는 어려움이 있습니다.

**Comment by MinjiK00** [comment]
넵, 검토 감사합니다.
