### ISSUE TITLE
v5.1.12 프로그램 셧다운 오류

### ISSUE THREAD

**Issue by MinjiK00** [EgisCorp/XDWORLD-Builder-Professional#89]
안녕하세요.
프로그램 실행 시 간혹 저절로 프로그램이 셧다운되는 오류가 있습니다.
PC 부팅 후 첫 실행 시 셧다운 되는 경우가 잦았으며, 배경지도가 기본적으로 표출되기 전 프로그램이 종료되었습니다.
문제 확인 부탁드립니다.
![그림1-down](https://github.com/user-attachments/assets/7079985e-f1e6-450d-9f3a-d5bf9ced441e)

**Comment by YangHeeBong** [comment]
혹시 언제 v5.1.12 설치본을 받으셨나요? 

초기 v5.1.12 업데이트 후 관련 문제를 확인 하고 제 업로드를 통해 빌더가 강제종료되는 문제를 해결하였습니다. 

만약 2024년 11월 18일 오후 이전에 받으셨다면 릴리즈 설치본을 받아서 재 설치를 통해 관련 문제를 해결할 수 있습니다.

**Comment by MinjiK00** [comment]
재설치하여 정상 실행되는 점 확인했습니다. 감사합니다.
